Add --dry-run support to git-cleanup-branches

diff --git a/git-cleanup-branches b/git-cleanup-branches
--- a/git-cleanup-branches
+++ b/git-cleanup-branches
@@ -1,14 +1,39 @@
 #!/usr/bin/env bash
 
-base_branch=$1
-if [[ "$base_branch" == "--help" ]]; then
-    echo "Usage: $0 [base-branch-name]"
-    echo "Prompts for removing branches that are merged into a specified base branch."
-    exit 1
+progname=${0##*/}
+# shellcheck disable=SC1091
+source getopt.bash "n" "dry-run" "$progname" "$@"
+
+base_branch=""
+dry_run=0
+
+while true; do
+    opt=$1
+    shift
+    case "$opt" in
+        -n|--dry-run)
+            dry_run=1
+            ;;
+        --)
+            break
+            ;;
+        *)
+            echo "Error: getopt was configured incorrectly."
+            echo "Error: Contact the author of '$progname'."
+            exit 3
+            ;;
+    esac
+done
+
+if [[ $# -gt 0 ]]; then
+    if [[ $# -gt 1 ]]; then
+        echo "Error: too many non-option arguments." >&2
+        exit 3
+    fi
+    base_branch="$1"
 fi
 
-branch_list="$(git branch --format='%(refname:short)')"
-if [[ -z "$base_branch" || "$branch_list" != *"$base_branch"* ]]; then
+if [[ "$base_branch" == "" ]]; then
     git branch --format='%(refname:short)'
     read -r -p "Which of the above branches do you want to treat as the base branch? " base_branch
 fi
@@ -20,6 +45,10 @@ fi
 # Get a list of all local branches that are merged into the base branch
 for branch in $(git branch --merged "${base_branch}" --format='%(refname:short)'); do
     if [[ "$branch" != "$base_branch" ]]; then
+        if [[ "$dry_run" -eq 1 ]]; then
+            echo "Would delete $branch"
+            continue
+        fi
         read -r -p "Do you want to remove $branch? (y/n) " answer
         if [[ "$answer" == "y" ]]; then
             git branch -d "$branch"
