Check for uncommitted changes in pull-branches

diff --git a/git-pull-branches b/git-pull-branches
--- a/git-pull-branches
+++ b/git-pull-branches
@@ -2,6 +2,18 @@
 
 [ "${1:0:2}" == "-v" ] && verbose=1
 
+if ! git diff --quiet; then
+	echo "error: cannot pull-branches: You have unstaged changes." >&2
+	echo "error: Please commit or stash them." >&2
+	exit 1
+fi
+
+if ! git diff --quiet --staged; then
+	echo "error: cannot pull-branches: Your index contains uncommitted changes." >&2
+	echo "error: Please commit or stash them." >&2
+	exit 1
+fi
+
 original_branch=$(git branch --show-current)
 if [ -z "$original_branch" ]; then
     original_branch=$(git rev-parse HEAD)
